using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace AlbumProject.Migrations
{
    public partial class FirstMigration : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Artists",
                columns: table => new
                {
                    Name = table.Column<string>(nullable: true),
                    Image = table.Column<string>(nullable: true),
                    Age = table.Column<int>(nullable: false),
                    Hometown = table.Column<string>(nullable: true),
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Artists", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Albums",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Title = table.Column<string>(nullable: true),
                    Image = table.Column<string>(nullable: true),
                    Label = table.Column<string>(nullable: true),
                    ArtistId = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Albums", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Albums_Artists_ArtistId",
                        column: x => x.ArtistId,
                        principalTable: "Artists",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Songs",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Title = table.Column<string>(nullable: true),
                    Duration = table.Column<string>(nullable: true),
                    AlbumId = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Songs", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Songs_Albums_AlbumId",
                        column: x => x.AlbumId,
                        principalTable: "Albums",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Artists",
                columns: new[] { "Id", "Age", "Hometown", "Image", "Name" },
                values: new object[,]
                {
                    { 1, 35, "Cleveland, Ohio", "/images/kidcudi.jpg", "Kid Cudi" },
                    { 2, 32, "Las Vegas, Nevada", "/images/imaginedragons.jpg", "Imagine Dragons" },
                    { 3, 54, "London, England", "/images/pinkfloyd.jpg", "Pink Floyd" },
                    { 4, 38, "New York, New York", "/images/alicia-keys.jpg", "Alicia Keys" }
                });

            migrationBuilder.InsertData(
                table: "Albums",
                columns: new[] { "Id", "ArtistId", "Image", "Label", "Title" },
                values: new object[,]
                {
                    { 1, 1, "/images/MotM1.jpg", "Universal Records", "Man On The Moon" },
                    { 18, 4, "/images/elementoffreedom.jpg", "J", "The Element of Freedom" },
                    { 17, 4, "/images/asiam.png", "J", "As I Am" },
                    { 16, 4, "/images/diaryofakeys.jpg", "J", "The Diary of Alicia Keys" },
                    { 15, 4, "/images/songsinaminor.jpg", "J", "Songs in A Minor" },
                    { 14, 3, "/images/dark-side-of-moon.jpg", "Harvest Records", "The Dark Side of the Moon" },
                    { 13, 3, "/images/The-Final-Cut.jpg", "Harvest Records", "The Final Cut" },
                    { 12, 3, "/images/Atom-Heart-Mother.jpg", "Harvest Records", "Atom Heart Mother" },
                    { 11, 3, "/images/The-Division-Bell.jpg", "EMI Records", "The Division Bell" },
                    { 10, 2, "/images/origins.jfif", " Kidinakorner and Interscope Records", "Origins" },
                    { 9, 2, "/images/evolve.jpg", " Kidinakorner and Interscope Records", "Evolve" },
                    { 8, 2, "/images/smokemirrors_720.jpg", " Kidinakorner and Interscope Records", "Smoke + Mirrors" },
                    { 7, 2, "/images/nightvisions.jpg", " Kidinakorner and Interscope Records", "Night Visions" },
                    { 6, 1, "/images/PP&DS.jpg", "Republic Records", "Passion, Pain & Demon Slayin" },
                    { 5, 1, "/images/SB2H.jpg", "Republic Records", "Speedin' Bullet 2 Heaven" },
                    { 4, 1, "/images/satellite.jpg", "Kid Cudi P/S", "Satellite Flight: The Journey to Mother Moon" },
                    { 3, 1, "/images/Indicud.jpg", "Republic Records", "Indicud" },
                    { 2, 1, "/images/MotM2.jpg", "Universal Motown Records", "Man On The Moon 2" },
                    { 19, 4, "/images/girlonfire.jpg", "RCA", "Girl on Fire" },
                    { 20, 4, "/images/here.jpg", "RCA", "Here" }
                });

            migrationBuilder.InsertData(
                table: "Songs",
                columns: new[] { "Id", "AlbumId", "Duration", "Title" },
                values: new object[,]
                {
                    { 1, 1, "3:15", "In My Dreams(Cudder Anthem)" },
                    { 176, 13, "4:09", "The Fletcher Memorial Home" },
                    { 177, 13, "2:13", "Southampton Dock" },
                    { 178, 13, "4:43", "The Final Cut" },
                    { 179, 13, "5:01", "Not Now John [Explicit]" },
                    { 180, 13, "5:15", "Two Suns in the Sunset" },
                    { 181, 14, "1:05", "Speak To Me/Breathe" },
                    { 182, 14, "3:45", "On The Run" },
                    { 183, 14, "6:54", "Time" },
                    { 184, 14, "4:44", "The Great Gig In The Sky" },
                    { 185, 14, "6:23", "Money" },
                    { 186, 14, "7:49", "Us And Them" },
                    { 187, 14, "3:26", "Any Colour You Like" },
                    { 188, 14, "3:47", "Brain Damage" },
                    { 189, 14, "2:10", "Eclipse" },
                    { 175, 13, "1:17", "Get Your Filthy Hands Off My Desert" },
                    { 190, 15, "1:52", "Piano & I" },
                    { 192, 15, "3:57", "How Come You Don't Call Me" },
                    { 193, 15, "3:30", "Fallin" },
                    { 194, 15, "4:28", "Troubles" },
                    { 195, 15, "5:36", "Rock wit U" },
                    { 196, 15, "5:03", "A Woman's Worth" },
                    { 197, 15, "3:48", "Jane Doe" },
                    { 198, 15, "4:20", "Goodbye" },
                    { 199, 15, "5:25", "The Life" },
                    { 200, 15, "4:09", "Mr. Man" },
                    { 201, 15, "2:01", "Never Felt This Way" },
                    { 202, 15, "4:08", "Butterflyz" },
                    { 203, 15, "4:25", "Why Do I Feel So Sad" },
                    { 204, 15, "3:02", "Caged Bird" },
                    { 205, 15, "3:49", "Lovin U" },
                    { 191, 15, "3:34", "Girlfriend" },
                    { 174, 13, "3:42", "Paranoid Eyes" },
                    { 173, 13, "5:18", "The Gunner's Dream" },
                    { 172, 13, "2:43", "The Hero's Return" },
                    { 141, 10, "3:08", "Boomerang" },
                    { 142, 10, "3:02", "Machine" },
                    { 143, 10, "3:38", "Cool Out" },
                    { 144, 10, "4:21", "Bad Liar" },
                    { 145, 10, "3:38", "West Coast" },
                    { 146, 10, "3:31", "Zero" },
                    { 147, 10, "3:25", "Bullet In A Gun" },
                    { 148, 10, "3:21", "Digital" },
                    { 149, 10, "3:01", "Only" },
                    { 150, 10, "3:11", "Stuck" },
                    { 151, 10, "2:47", "Love" },
                    { 152, 11, "5:56", "Cluster One" },
                    { 153, 11, "4:22", "What Do You Want From Me" },
                    { 154, 11, "7:03", "Poles Apart" },
                    { 155, 11, "5:30", "Marooned" },
                    { 156, 11, "4:17", "A Great Day For Freedom" },
                    { 157, 11, "6:49", "Wearing The Inside Out" },
                    { 171, 13, "3:12", "When the Tigers Broke Free" },
                    { 170, 13, "1:17", "One of the Few" },
                    { 169, 13, "4:26", "Your Possible Pasts" },
                    { 168, 13, "2:59", "The Post War Dream" },
                    { 167, 12, "12:59", "Alan's Psychedelic Breakfast" },
                    { 166, 12, "5:24", "Fat Old Sun" },
                    { 206, 16, "1:43", "Harlem's Nocturne" },
                    { 165, 12, "5:29", "Summer '68" },
                    { 163, 12, "23:41", "Atom Heart Mother" },
                    { 162, 11, "8:31", "High Hopes" },
                    { 161, 11, "5:15", "Lost For Words" },
                    { 160, 11, "6:11", "Keep Talking" },
                    { 159, 11, "6:19", "Coming Back To Life" },
                    { 158, 11, "6:12", "Take It Back" },
                    { 164, 12, "4:31", "If" },
                    { 207, 16, "4:16", "Karma" },
                    { 208, 16, "3:28", "Heartburn" },
                    { 209, 16, "3:06", "If I Was Your Woman / Walk On By" },
                    { 245, 18, "3:45", "This Bed" },
                    { 246, 18, "4:27", "Distance and Time" },
                    { 247, 18, "4:42", "How It Feels to Fly" },
                    { 248, 18, "3:36", "Empire State of Mind (Part II) Broken Down" },
                    { 249, 19, "1:19", "De Novo Adagio (Intro)" },
                    { 250, 19, "3:53", "Brand New Me" },
                    { 251, 19, "4:34", "When It's All Over" },
                    { 252, 19, "3:46", "Listen to Your Heart" },
                    { 253, 19, "4:02", "New Day" },
                    { 254, 19, "4:30", "Girl on Fire" },
                    { 255, 19, "5:21", "Fire We Make" },
                    { 256, 19, "3:59", "Tears Always Win" },
                    { 257, 19, "3:07", "Not Even the King" },
                    { 258, 19, "4:05", "That's When I Knew" },
                    { 259, 19, "3:57", "Limitedless" },
                    { 260, 19, "4:08", "One Thing" },
                    { 261, 19, "6:29", "101" },
                    { 275, 20, "4:35", "More than We Know" },
                    { 274, 20, "0:25", "You Glow (interlude)" },
                    { 273, 20, "2:39", "Girl Can't Be Herself" },
                    { 272, 20, "0:59", "Cocoa Butter (Cross & Pic Interlude)" },
                    { 271, 20, "3:34", "Work on It" },
                    { 270, 20, "3:31", "Blended Family (What You Do for Love)" },
                    { 244, 18, "3:15", "Put It in a Love Song" },
                    { 269, 20, "5:23", "Illusion of Bliss" },
                    { 267, 20, "6:07", "She Don't Really Care/1 Luv" },
                    { 266, 20, "2:40", "Kill Your Mama" },
                    { 265, 20, "0:50", "Elain Brown (interlude)" },
                    { 264, 20, "3:10", "Pawn It All" },
                    { 263, 20, "3:01", "The Gospel" },
                    { 262, 20, "1:04", "The Beginning" },
                    { 268, 20, "0:48", "Elevate (interlude)" },
                    { 140, 10, "3:10", "Natural" },
                    { 243, 18, "4:13", "Like the Sea" },
                    { 241, 18, "4:09", "Un-Thinkable (I'm Ready)" },
                    { 210, 16, "6:06", "You Don't Know My Name" },
                    { 211, 16, "3:48", "If I Ain't Got You" },
                    { 212, 16, "4:45", "Diary" },
                    { 213, 16, "4:36", "Dragon Days" },
                    { 214, 16, "4:27", "Wake Up" },
                    { 215, 16, "3:49", "So Simple" },
                    { 216, 16, "4:09", "When You Really Love Someone" },
                    { 217, 16, "2:07", "Feeling U, Feeling Me" },
                    { 218, 16, "4:18", "Slow Down" },
                    { 219, 16, "4:12", "Samsonite Man" },
                    { 220, 16, "2:56", "Nobody Not Really" },
                    { 221, 17, "1:52", "As I Am (Intro)" },
                    { 222, 17, "4:36", "Go Ahead" },
                    { 223, 17, "4:34", "Superwoman" },
                    { 224, 17, "4:12", "No One" },
                    { 225, 17, "5:15", "Like You'll Never See Me Again" },
                    { 226, 17, "4:14", "Lesson Learned" },
                    { 240, 18, "4:04", "That's How Strong My Love Is" },
                    { 239, 18, "4:01", "Wait Til You See My Smile" },
                    { 238, 18, "4:09", "Try Sleeping with a Broken Heart" },
                    { 237, 18, "4:32", "Doesn't Mean Anything" },
                    { 236, 18, "3:49", "Love is Blind" },
                    { 235, 18, "0:12", "The Element of Freedom (Intro)" },
                    { 242, 18, "4:01", "Love Is My Disease" },
                    { 234, 17, "4:31", "Sure Looks Good to Me" },
                    { 232, 17, "2:08", "Prelude to a Kiss" },
                    { 231, 17, "4:11", "Where Do We Go from Here" },
                    { 230, 17, "5:10", "I Need You" },
                    { 229, 17, "3:10", "Teenage Love Affair" },
                    { 228, 17, "3:50", "The Thing About Love" },
                    { 227, 17, "3:53", "Wreckless Love" },
                    { 233, 17, "4:28", "Tell You Something (Nana's Reprise)" },
                    { 276, 20, "2:47", "Where Do We Begin Now" },
                    { 139, 9, "3:54", "Dancing In The Dark" },
                    { 137, 9, "3:08", "Thunder" },
                    { 37, 3, "4:16", "King Wizard" },
                    { 38, 3, "5:02", "Immortal" },
                    { 39, 3, "3:34", "Solo Dolo Part II " },
                    { 40, 3, "4:28", "Girls" },
                    { 41, 3, "1:53", "New York City Rage Fest" },
                    { 42, 3, "3:55", "Red Eye" },
                    { 43, 3, "4:09", "Mad Solar" },
                    { 44, 3, "3:13", "Beez" },
                    { 45, 3, "4:41", "Brothers" },
                    { 46, 3, "2:58", "Burn Baby Burn" },
                    { 47, 3, "2:47", "Lord Of The Sad And Lonely" },
                    { 48, 3, "2:32", "Cold Blooded" },
                    { 49, 3, "9:03", "Afterwards (Bring Yo Friends)" },
                    { 50, 3, "2:51", "The Flight Of The Moon Man" },
                    { 36, 3, "4:24", "Young Lady" },
                    { 51, 4, "1:50", "Destination: Mother Moon" },
                    { 53, 4, "4:35", "SATELLITE FLIGHT" },
                    { 54, 4, "4:34", "Copernicus Landing" },
                    { 55, 4, "5:27", "Balmain Jeans" },
                    { 56, 4, "6:18", "Too Bad I Have To Destroy You Now" },
                    { 57, 4, "4:16", "Internal Bleeding" },
                    { 58, 4, "1:46", "In My Dreams 2015" },
                    { 59, 4, "5:15", "Return Of The Moon Man" },
                    { 60, 5, "3:21", "Troubled Boy" },
                    { 61, 5, "4:43", "Edge Of The Earth/Post Mortem Boredom" },
                    { 62, 5, "3:56", "CONFUSED!" },
                    { 63, 5, "3:50", "Man In The Night" },
                    { 64, 5, "2:28", "Screwed" },
                    { 65, 5, "2:58", "Fade 2 Red" },
                    { 66, 5, "6:10", "Adventures" },
                    { 52, 4, "3:48", "Going To The Ceremony" },
                    { 35, 3, "3:48", "Just What I Am" },
                    { 34, 3, "4:36", "Unfuckwittable" },
                    { 33, 3, "2:41", "The Resurrection Of Scott Mescudi" },
                    { 2, 1, "3:56", "Soundtrack 2 My Life" },
                    { 3, 1, "2:32", "Simple As…" },
                    { 4, 1, "4:26", "Solo Dolo (Nightmare)" },
                    { 5, 1, "4:21", "Heart Of A Lion" },
                    { 6, 1, "4:03", "My World" },
                    { 7, 1, "3:42", "Day ‘N’ Nite (nightmare)" },
                    { 8, 1, "3:41", "Sky Might Fall" },
                    { 9, 1, "4:20", "Enter Galactic (Love Connection Part 1)" },
                    { 10, 1, "4:06", "Alive (Nightmare)" },
                    { 11, 1, "3:36", "Make Her Say" },
                    { 12, 1, "4:55", "Pursuit Of Happiness (Nightmare)" },
                    { 13, 1, "3:32", "Hyyerr" },
                    { 14, 1, "3:46", "Up Up & Away" },
                    { 15, 1, "3:46", "In My Dreams(Cudder Anthem)" },
                    { 16, 2, "3:55", "Scott Mesucdi Vs The World" },
                    { 17, 2, "3:03", "REVOFEV" },
                    { 18, 2, "3:43", "Don’t Play This Song" },
                    { 32, 2, "3:33", "Trapped In My Mind" },
                    { 31, 2, "4:49", "GHOST!" },
                    { 30, 2, "3:23", "All Along" },
                    { 29, 2, "4:20", "The End" },
                    { 28, 2, "4:16", "These Worries" },
                    { 27, 2, "4:54", "Mr. Rager" },
                    { 67, 5, "3:31", "The Nothing" },
                    { 26, 2, "2:58", "MANIAC" },
                    { 24, 2, "4:14", "Wild’n Cuz I’m Young" },
                    { 23, 2, "3:12", "Erase Me" },
                    { 22, 2, "3:48", "Ashin’ Kusher" },
                    { 21, 2, "3:31", "Mojo So Dope" },
                    { 20, 2, "4:20", "Marijuana" },
                    { 19, 2, "1:27", "We Aite (Wake Your Mind Up)" },
                    { 25, 2, "2:36", "The Mood" },
                    { 68, 5, "3:04", "AMEN" },
                    { 69, 5, "3:45", "Handle With Care" },
                    { 70, 5, "3:05", "Judgemental C**t" },
                    { 106, 7, "3:14", "Tiptoe" },
                    { 107, 7, "4:01", "It's Time" },
                    { 108, 7, "2:58", "Demons" },
                    { 109, 7, "3:10", "On Top Of The World" },
                    { 110, 7, "4:02", "Amsterdam" },
                    { 111, 7, "3:53", "Hear Me" },
                    { 112, 7, "3:36", "Every Night" },
                    { 113, 7, "3:42", "Bleeding Out" },
                    { 114, 7, "3:27", "Underdog" },
                    { 115, 7, "8:57", "Nothing Left To Say/Rocks" },
                    { 116, 8, "3:53", "Shots" },
                    { 117, 8, "3:37", "Gold" },
                    { 118, 8, "4:21", "Smoke And Mirrors" },
                    { 119, 8, "3:51", "I'm So Sorry" },
                    { 120, 8, "3:12", "I Bet My Life" },
                    { 121, 8, "3:52", "Polaroid" },
                    { 122, 8, "3:22", "Friction" },
                    { 136, 9, "3:42", "Mouth Of The River" },
                    { 135, 9, "3:26", "Yesturday" },
                    { 134, 9, "4:23", "I'll Make It Up To You" },
                    { 133, 9, "3:52", "Rise Up" },
                    { 132, 9, "3:53", "Walking The Wire" },
                    { 131, 9, "3:25", "Believer" },
                    { 105, 7, "3:07", "Radioactive" },
                    { 130, 9, "3:22", "Whatever It Takes" },
                    { 128, 8, "6:03", "The Fall" },
                    { 127, 8, "4:02", "Hopeless Opus" },
                    { 126, 8, "3:39", "Summer" },
                    { 125, 8, "3:13", "Trouble" },
                    { 124, 8, "4:19", "Dream" },
                    { 123, 8, "3:38", "It Comes Back To You" },
                    { 129, 9, "3:11", "I Don't Know Why" },
                    { 138, 9, "3:27", "Star Over" },
                    { 104, 6, "6:15", "Surfin’" },
                    { 102, 6, "5:06", "The Guide" },
                    { 71, 5, "1:54", "Seance Chaos" },
                    { 72, 5, "3:06", "Fairy Tale Remains" },
                    { 73, 5, "2:32", "Wedding Tux" },
                    { 74, 5, "3:30", "Angered Kids" },
                    { 75, 5, "4:38", "Red Sabbath" },
                    { 76, 5, "2:45", "Fuchsia Butterflies" },
                    { 77, 5, "4:35", "Speedin Bullet 2 Heaven" },
                    { 78, 5, "3:01", "Embers" },
                    { 79, 5, "4:35", "Anomaly" },
                    { 80, 5, "4:15", "The Return of Chip Douglas" },
                    { 81, 5, "2:44", "Trauma" },
                    { 82, 5, "1:58", "WAIT" },
                    { 83, 5, "3:07", "Insides Out" },
                    { 84, 5, "3:24", "Speedin’ Bullet 2 Heaven" },
                    { 85, 5, "5:17", "Worth" },
                    { 86, 5, "4:58", "Frequency" },
                    { 87, 6, "4:29", "Swim In The Light" },
                    { 101, 6, "4:01", "Cosmic Warrior" },
                    { 100, 6, "4:29", "Kitchen" },
                    { 99, 6, "3:55", "Mature Nature" },
                    { 98, 6, "4:03", "Wounds" },
                    { 97, 6, "4:47", "Distant Fantasies" },
                    { 96, 6, "4:43", "Dance 4 Eternity" },
                    { 103, 6, "4:16", "The Commander" },
                    { 95, 6, "4:23", "Does It" },
                    { 93, 6, "4:45", "Baptized In Fire" },
                    { 92, 6, "4:38", "Rose Golden" },
                    { 91, 6, "4:16", "ILLusions" },
                    { 90, 6, "4:11", "All In" },
                    { 89, 6, "4:17", "By Design" },
                    { 88, 6, "5:28", "Releaser" },
                    { 94, 6, "3:57", "Flight At First Sight/Advanced" },
                    { 277, 20, "4:22", "Holy War" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Albums_ArtistId",
                table: "Albums",
                column: "ArtistId");

            migrationBuilder.CreateIndex(
                name: "IX_Songs_AlbumId",
                table: "Songs",
                column: "AlbumId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Songs");

            migrationBuilder.DropTable(
                name: "Albums");

            migrationBuilder.DropTable(
                name: "Artists");
        }
    }
}
